### ISSUE TITLE
Chained field name for Select

### ISSUE THREAD

**Issue by dmitry-izmerov** [instancio/instancio#1001]
### Feature description

It would be great to select field based on dot separated chain of fields like "student.address.street", so that you can set value for nested field.
Example of Select:
`Select.field(Student.class, "student.address.street")`

**Comment by armandino** [comment]
@dmitry-izmerov thank you for the suggestion. Just out of interest, do you have a use case that cannot be resolved using existing selectors? e.g.

```java
Select.field(Address.class, "street")
// or with scope
Select.field(Address.class, "street").within(scope(Student.class))
```

**Comment by dmitry-izmerov** [comment]
@armandino thanks for clarification, I did not see the second approach

**Comment by armandino** [comment]
@dmitry-izmerov no worries. You can find more examples in the user guide: https://www.instancio.org/user-guide/#selectors
