### ISSUE TITLE
Add support for Hibernate Validator `@INN` annotation

### ISSUE THREAD

**Issue by armandino** [instancio/instancio#1004]
### Feature description

Checks that the annotated character sequence represents a Russian taxpayer identification number. Can be applied to both individual and juridical versions of INN

-  Supported data types: `CharSequence`
- Country:  Russia

Docs: https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#_country_specific_constraints

`@REGON` implementation can be used for reference (`RegonGeneratorSpec` and `RegonSpec`).

**Comment by EvaristeGalois11** [comment]
Hi :D

The last hibernate validators were pretty fun to work on, I'll gladly take this issue!

**Comment by armandino** [comment]
@EvaristeGalois11 thank you and welcome back! :)

**Comment by brunodmartins** [comment]
@EvaristeGalois11 I added the Brazil classes to start supporting those generators. CPF and CNPJ are already implemented, you can rebase to just add the generator class for INN

**Comment by EvaristeGalois11** [comment]
Thank you for the heads up @brunodmartins!
