### ISSUE TITLE
 Add support for Hibernate Validator `@TituloEleitoral` annotation

### ISSUE THREAD

**Issue by armandino** [instancio/instancio#1005]
### Feature description

Checks that the annotated character sequence represents a Brazilian voter ID card number ([Título Eleitoral](http://www.exceldoseujeito.com.br/2008/12/19/validar-cpf-cnpj-e-titulo-de-eleitor-parte-ii/))

- Supported data types: `CharSequence`
- Country:  Brazil

Docs: https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#_country_specific_constraints

`@REGON` implementation can be used for reference (`RegonGeneratorSpec` and `RegonSpec`).

**Comment by brunodmartins** [comment]
I will grab it =)

**Comment by brunodmartins** [comment]
@armandino I am having some issue with the Hibernate validator library! It seems that its not correct validating the Titulo Eleitoral!. I validated that bug against a [Brazilian Website](https://www.4devs.com.br/validador_titulo_de_eleitor), and through manual tests using an Excel formula. Here are some examples that fails on Hibernate:

- 975993331007, 524384240701, 311533282500, 083578481406, 233838490205

I will check if there is a Hibernate bug for that, and push the code that I have without the usage of Hibernate Validator for now.

**Comment by brunodmartins** [comment]
I opened an issue on Hibernate-Validator for this bug.

PR: https://github.com/hibernate/hibernate-validator/pull/1371
Jira: https://hibernate.atlassian.net/browse/BVAL-791

**Comment by armandino** [comment]
@brunodmartins I did a quick search, and @TituloEleitoral has been available for at least 10 years (since Hibernate 4). It's interesting that this issue has not been reported until now. Great catch!

**Comment by brunodmartins** [comment]
Yeah! It's weird...although, this number is often only needed on elections and used on government programs (that are mostly using old Java technology or .NET). This could explain why it hasn't been catch
