### ISSUE TITLE
Add support for Hibernate Validator `@CPF` annotation

### ISSUE THREAD

**Issue by armandino** [instancio/instancio#1006]
### Feature description

Checks that the annotated character sequence represents a Brazilian individual taxpayer registry number (Cadastro de Pessoa Física).

- Supported data types: `CharSequence`
- Country:  Brazil

Docs: https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#_country_specific_constraints

`@REGON` implementation can be used for reference (`RegonGeneratorSpec` and `RegonSpec`).

**Comment by brunodmartins** [comment]
I want to work on this issue!

**Comment by armandino** [comment]
@brunodmartins thank you for taking this on!

A couple of links that might help you get started:

- https://www.instancio.org/building/
- https://github.com/instancio/instancio/blob/main/CONTRIBUTING.md

**Comment by brunodmartins** [comment]
Thanks! I am working on a PR right now!

**Comment by brunodmartins** [comment]
I opened the PR. I used the SSN generator as a guide to implement the CPF generation, and after that, I added the Bean validation. I can work on the other two BR issues too! #1007 #1005
