### ISSUE TITLE
Add support for Hibernate Validator `@CNPJ` annotation

### ISSUE THREAD

**Issue by armandino** [instancio/instancio#1007]
### Feature description

Checks that the annotated character sequence represents a Brazilian corporate tax payer registry number (Cadastro de Pessoa Jurídica).

- Supported data types: `CharSequence`
- Country:  Brazil

Docs: https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#_country_specific_constraints

`@REGON` implementation can be used for reference (`RegonGeneratorSpec` and `RegonSpec`).

**Comment by brunodmartins** [comment]
I want to work on this issue!

**Comment by brunodmartins** [comment]
I will grab this issue, ok?

**Comment by armandino** [comment]
@brunodmartins sure thing. Thank you!
