### ISSUE TITLE
InstancioExtension should be made aware of `MANUAL` and  `WITH_SETTINGS_BUILDER` seed sources

### ISSUE THREAD

**Issue by elkkhan** [instancio/instancio#1026]
**Describe the bug**
Currently, `InstancioExtension` is only [made aware of](https://github.com/instancio/instancio/blob/bc08cf308a8d49c44a3f9ab781ffdc2ee5187ad8/instancio-junit/src/main/java/org/instancio/junit/internal/ExtensionSupport.java#L51-L81) seeds that are set via either of:
- `@WithSettings`
- `@Seed`
- `instanctio.properties`

**Actual result**
Scenario:
- Seed is set via `InstanctioApi.withSeed`
- JUnit test is using the `InstancioExtension` and supplies a seed using `@Seed`
- An object is generated using the model from step 1
- The seed provided with `@Seed` is ignored and the seed from step 1 takes precedence (this is expected behaviour)
- Test fails
- Instancio [logs](https://github.com/instancio/instancio/blob/ab19981cc1878101b78e284f1c81820af61071f5/instancio-junit/src/main/java/org/instancio/junit/InstancioExtension.java#L135-L136) the seed that was provided with `@Seed`, which is incorrect and confusing

**Expected result**
- Specifying seed from multiple sources should not be allowed, OR
- `InstancioExtension` should log the correct seed that was used during object generation

Java version: 21
Instancio version: 4.5.1

**Comment by elkkhan** [comment]
I can actually see that [it's intentional](https://github.com/instancio/instancio/blob/bc08cf308a8d49c44a3f9ab781ffdc2ee5187ad8/instancio-tests/instancio-junit-tests/src/test/java/org/instancio/junit/InstancioExtensionThreadLocalRandomTest.java#L94-L95) but I don't understand the reasoning behind it

**Comment by armandino** [comment]
Thanks for raising this issue. Can you please take a look at this issue to see if it answers your question?

- #940

**Comment by elkkhan** [comment]
Hi @armandino, thanks, it does clarify this alot but I still think there is an issue here.
I understand the reasoning behind not reporting a seed that was set explicitly via non-annotation settings because it is known to the user anyway, but consider an example where:
```java
model.withSeed(System.nanoTime())
```
this is not a constant value and the value is not known to the user.

I think it gets a little confusing when both `@Seed` and `.withSeed(seed)` or `setting(Keys.SEED, seed)` are used together:

```java
@Seed(123)
@Test
void test() {
    Instancio.of(String.class).withSeed(321).create();
    assertThat(1).isEqualTo(2);
}
```
this will log out the seed `123` while this seed was not used at all.
It is definitely a user error to specify `@Seed` and then not use it, but I think it could be nice to prevent this from happening.

I like the `Result<>.getSeed()` solution from the issue you linked so I will use that in my usecase. Feel free to close the issue if you think the above is not feasible

**Comment by armandino** [comment]
@elkkhan thank you for the additional feedback. Just to understand your use case a little bit better, is there a reason you need to use `withSeed()` in your test? Typically, users shouldn't need to set the seed manually via `withSeed()` when using the `InstancioExtension`.

Currently, the reported seed value is all that's needed to reproduce the entire test method's data. This assumes you don't use `System.nanoTime()` or `java.util.Random` directly (such usage is not supported).

One of the issues with logging all the seeds is that it will be confusing if a test method creates many objects.  Building on your example, if we create 3 strings:

```java
@Seed(123)
@Test
void test() {
    Instancio.of(String.class).withSeed(321).create();
    Instancio.of(String.class).withSeed(456).create();
    Instancio.of(String.class).withSeed(567).create();
    assertThat(1).isEqualTo(2);
}
```

> "test() failed with seeds: 123, 321, 456, 567"

compared to current behaviour:

> "test() failed with seed: 123"

Regardless of the manual seeds, `123` is the only thing that's needed to reproduce the test.
