### ISSUE TITLE
`instancio-quickcheck`: docs misuse "property" term

### ISSUE THREAD

**Issue by commonquail** [instancio/instancio#1031]
The Instancio Quickcheck module documentation at <https://www.instancio.org/user-guide/#quickcheck> uses the phrases

> The test case verifies that one of the properties of the `Person` type (in this case `age` property) should be a strictly positive number for any generated `Person` instance.

> a custom property generation strategy can be provided:

> the `@Property` annotation denotes an individual test case with the possibility to set the number of samples to generate for each property in question

> the `@ForAll` annotation on test case method argument denotes the individual property to generate samples against

> The test engine inspects all accessible instance methods of the test class to find out the candidates for the properties under test

That is, the Instancio Quickcheck module uses "property" synonymously with what Java calls a field or a component.

But this is not at all what "property" means in "[property testing](https://en.wikipedia.org/wiki/Software_testing#Property_testing)" or in the Haskell QuickCheck library that defined property testing or in the QuickCheck research paper the Instancio documentation appeals to or in <https://www.schoolofhaskell.com/user/pbv/an-introduction-to-quickcheck-testing>. The meaning of "property" here is closer to that of "fact" or "truth" or "invariant": "given some general input state, this general output state is guaranteed". For example, "the reversal of the reversal of an input is equal to the input" is a property that holds for all lists.

Applied to the examples from the Instancio user guide, replicated here for posterity:

```java
@DisplayName("Test that each person has valid age")
@Property(samples = 100)
public void age(@ForAll Person p) {
    assertThat(i.age()).isGreaterThan(0);
}
```

```java
@DisplayName("Test that each person has valid age")
@Property(samples = 100)
public void age(@ForAll("persons") Person p) {
    assertThat(i.age()).isGreaterThan(0);
}

public Arbitrary<Person> persons() {
    return Arbitrary
        .fromStream(Stream.generate(() -> Instancio
            .of(Person.class)
            .generate(Select.field(Person::age), gen -> gen.ints().min(1).max(150))
            .create()));
}
```

- The "property" expressed is something like "a person's age is valid".
- `@ForAll` seems redundant. `@Property` has already marked the case for property testing, which implies generated input for all of which the assertion must be satisfied. I recognize that in the second example `@ForAll` also selects a generation strategy but there is no clear reason this could not be solved by `@Property` or a counterpart to JUnit 5's `@MethodSource`.

"A person's age is valid" is a poorly expressed property -- what does age validity entail? Examples of more clearly expressed properties that relate to the user guide's second example are

```java
public void age_is_not_negative(Person p) {}
public void age_does_not_exceed_150(Person p) {}
```

Unrelated to misusing the terminology, the second example also suffers from being tautological. It is plainly evident that if one generates an integer in the range [1 ; 150] then that integer is greater than 0. This weakness makes it much more difficult to understand what problem property testing solves and why Instancio's bid is useful. In fact, the second example can be trivially replicated with a plain JUnit 5 `@ParametrizedTest` and core Instancio (and it would still be tautological), i.e. `instancio-quickcheck` contributes nothing worthwhile.

Properties generally (always?) refer to behavior, not state, and thinking up meaningful and instructive behavior for a `Person` -- , which is probably just a POJO anyway -- is not easy for me. Even the example of "age ∈ [1 ; 150]" I could call into question: what is the age of a new-born baby? One could instead say something like "a person's full name starts with their given name, ends with their family name" but that statement would also be false in half the world. Rather than awkwardly shoehorn `Person` into these examples, <https://www.schoolofhaskell.com/user/pbv/an-introduction-to-quickcheck-testing> has multiple unfalsifiable and comprehensible examples of properties and property testing.

**Comment by commonquail** [comment]
> Would you be interested in submitting a PR?

Unfortunately my employment situation makes that difficult. This is only what I can easily do.

> I'm also curious if you had a chance to use the quickcheck module and if you have any feedback on it as well?

Genuinely valuable feedback, I'm not sure. I don't have any projects where the approach is a particularly strong candidate, mainly academic interest. But I did whip up the following two implementations I believe to be morally equivalent:

```java
final class ObjectMapperInstancioTest {

    private final ObjectMapper objectMapper = objectMapper();

    @Property(samples = 5)
    void ser_deser_roundtrips(Person input) throws JsonProcessingException {
        var s = objectMapper.writerFor(input.getClass()).writeValueAsString(input);
        var deser = objectMapper.readerFor(input.getClass()).readValue(s);
        assertThat(deser).isEqualTo(input);
    }
}

final class ObjectMapperJunitTest {

    private final ObjectMapper objectMapper = objectMapper();

    @ParameterizedTest
    @MethodSource("args")
    void ser_deser_roundtrips(Person input) throws JsonProcessingException {
        var s = objectMapper.writerFor(input.getClass()).writeValueAsString(input);
        var deser = objectMapper.readerFor(input.getClass()).readValue(s);
        assertThat(deser).isEqualTo(input);
    }

    public static Stream<Person> args() {
        return Instancio.of(Person.class).stream().limit(5);
    }
}

record Person(Name name, List<Address> addresses, List<ContactInfo> contactInfo) {}
record Name(String name) {}
record Address(String street, Country country) {}
record Country(String code) {}
interface ContactInfo {
    String get();
    record Phone(String phoneNumber) implements ContactInfo {
        @Override
        public String get() {
            return phoneNumber;
        }
    }
    record Email(String emailAddress) implements ContactInfo {
        @Override
        public String get() {
            return emailAddress;
        }
    }
}
```

When executed that looks like

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running example.ObjectMapperInstancioTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.273 s -- in example.ObjectMapperInstancioTest
[INFO] Running example.ObjectMapperJunitTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.099 s -- in example.ObjectMapperJunitTest
```

In this example, using serial execution, the execution time of `@Property` is substantially higher than that of `@ParameterizedTest`. However, at a hundred samples the overhead no longer dominates and `@Property` runs much faster than `@ParameterizedTest`. On the other hand, `@ParameterizedTest` is parallelizable and requires 1000 samples to reach the execution time of `@Property` under parallel execution. It is unfortunate the sample size is not reported in the output -- that misrepresents the amount of work the quickcheck module has to perform.

The quickcheck module makes it extremely easy and safe to perform this exact type of check. JUnit's parameterized test (JUnit 5 as well as JUnit 4) requires more ceremony that's more baroque, and at one point I accidentally changed only one of the three names that reference the parameter type and got a class cast exception. That's pretty cool.

As soon as I need to customize Instancio's behaviour, however, the playing field levels out. I can inject `Settings` with `@WithSettings` easily enough but there is no setting for printing out the seed, for example, and I don't have an `InstancioApi<T>` handle to invoke `verbose()` on. In the JUnit 5 `@MethodSource` implementation that's trivial, as it would be in a hypothetical `ArbitraryGenerator<T>` implementation. Customization also comes into play with subtype mapping, which is relevant for the `ContactInfo` interface -- it seems likely that it will frequently be necessary in practice to implement a generator.

`@Property` appears to Just Work™ with multiple parameters. `@ParameterizedTest`, in comparison, is very cumbersome with multiple parameters.

**Comment by armandino** [comment]
@commonquail thank you, I appreciate the feedback!

The quickcheck module is still labelled as "experimental" and is missing some essential features, such as reporting the seed, as you mentioned. Unfortunately, I haven't had much time to dedicate to it, as the core library already takes much of my time. I'm looking for other contributors to help drive it forward.

Additionally, there's the excellent [jqwik](https://github.com/jqwik-team/jqwik) library that has been around for a long time and offers similar functionality with more features. IMO, for `instancio-quickcheck` to justify its existence, it needs to provide something that jqwik doesn't. Here too, I'm looking for feedback from users to help drive it forward (or not).

**Comment by armandino** [comment]
@commonquail I updated the user guide. If you have any other feedback, please let me know.

**Comment by commonquail** [comment]
That looks pretty good!
