### ISSUE TITLE
Support for exclude

### ISSUE THREAD

**Issue by abaddoncoder** [instancio/instancio#1059]
For the built-in generator, can it support functions like "exclude"? For example, when generating integers, I expect to be able to use it like this:
gen.ints().range(1, 10).exclude(7, 8)

**Comment by armandino** [comment]
@abaddoncoder thanks for the suggestion. if you're generating numeric values, you can specify multiple ranges, e.g.

```java
generate(selector, gen -> gen.ints().range(1, 6).range(9, 10))
```

To exclude values in general, you can use the `filter()` method, e.g.

```java
filter(selector, (Integer i) -> i != 7 && i != 8)
```

https://www.instancio.org/user-guide/#using-filter

Does this work for your use case?

**Comment by armandino** [comment]
@abaddoncoder awesome, thank you. I'll close this issue then.
