### ISSUE TITLE
`@Seed` not recognized in both test methods

### ISSUE THREAD

**Issue by BoardsOfBielefeld** [instancio/instancio#1128]
As you can see in the following code snippet, two test methods are annotated with the same seed.

``` java
@ExtendWith(InstancioExtension.class)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class DummyTest {

    @Test
    @Order(1)
    @Seed(1118162188242661009L)
    void checkInstancioSeed_withResult() {
        var instancio = Instancio.of(Foo.class);
        System.out.println("seed = " + instancio.asResult().getSeed());
        var foo = instancio.create();

        assertThat(foo.value()).isEqualTo(3969);
    }

    @Test
    @Order(2)
    @Seed(1118162188242661009L)
    void checkInstancioSeed_withoutResult() {
        var foo = Instancio.of(Foo.class).create();

        assertThat(foo.value()).isEqualTo(3969);
    }

}

record Foo(int value) { }
```

I expected both methods to set the same value (3969) for the same seed, but in my setup, they repeatedly differ.
The second method raises an org.opentest4j.AssertionFailedError: 

    expected: 3969
     but was: 8667

Is this the expected behaviour? 

My Setup:
- Java 21
- Instancio instancio-junit:4.8.1
- Started in IntelliJ IDEA 2024.1 (Ultimate Edition)
- Windows 11

**Comment by armandino** [comment]
The reason you're seeing different results is because the two test methods are not the same.

- `Order(1)` method creates two objects: first one with `asResult()`, and the second with `create()`.
- `Order(2)` method creates one object.

If you update the methods to be the same, it should produce the same results:


```java
    @Test
    @Order(1)
    @Seed(1118162188242661009L)
    void checkInstancioSeed_withResult() {
        var result = Instancio.of(Foo.class)
                .asResult();

        System.out.println("seed = " + result.getSeed());
        var foo = result.get();

        assertThat(foo.value()).isEqualTo(8667);
    }

    @Test
    @Order(2)
    @Seed(1118162188242661009L)
    void checkInstancioSeed_withoutResult() {
        var foo = Instancio.of(Foo.class).create();

        assertThat(foo.value()).isEqualTo(8667);
    }
```

**Comment by BoardsOfBielefeld** [comment]
Oh, my fault. Thanks a lot for your quick answer, @armandino .
