### ISSUE TITLE
Instancio.ofCartesianProduct and ofSet do not work with enum fields

### ISSUE THREAD

**Issue by zburak** [instancio/instancio#1131]
**Describe the bug**
If target class has enum fields and those fields are explicitly set with `.set(field("fieldName"), ENUM_VALUE)` or `.with(field("yourField"), ENUM_VAL, ENUM_VAL2)` , collection generation is failed for Instancio.ofCartesianProduct, Instancio.ofSet and most likely for other collection types.

**Expected result**
Enum fields are properly set while generating collection

**Actual result**
Collection creation fails with following reason
Reason: invalid field 'myField' for interface java.util.List

**Link to a minimal sample project reproducing the issue or runnable sample code**
```java
record TestRecord(String recordName,
                         String originalName, MyEnum myField, YourEnum yourField) {}

enum MyEnum {
  VAL_1,
  VAL_2
}

enum YourEnum{
  VAL_3,
  VAL_4
}

@Test
  void testCartesian() {
    List<TestRecord> testRecords = Instancio.ofCartesianProduct(TestRecord.class)
      .with(field("myField"), MyEnum.VAL_1, MyEnum.VAL_2)
      .with(field("yourField"), YourEnum.VAL_3, YourEnum.VAL_4)
      .create();
    Assertions.assertEquals(4, testRecords.size());
  }
```

- Java version: 17
- Instancio version: 5.0.1

**Comment by armandino** [comment]
@zburak the error is thrown because when you use the `field(String fieldName) ` selector, the field name is assumed to belong to the root object (in this case it's the `List`). Since `List` has no such field, you get the error.

Try using `field(TestRecord::myField)` or `field(TestRecord.class, "myField")` instead:

```java
List<TestRecord> testRecords = Instancio.ofCartesianProduct(TestRecord.class)
        .with(field(TestRecord::myField), MyEnum.VAL_1, MyEnum.VAL_2)
        .with(field(TestRecord::yourField), YourEnum.VAL_3, YourEnum.VAL_4)
        .create();
```

Please the docs for more info: https://www.instancio.org/user-guide/#selectors
