### ISSUE TITLE
jakarta.validation.constraints.@NotNull properties are null in generated instance

### ISSUE THREAD

**Issue by markrouz** [instancio/instancio#1145]
**Describe the bug**
After generation an instance with ` Instancio.of(...)`
some `@NotNull` fields are null
			
**Expected result**
properties are null

**Actual result**
properties should not be null

**Link to a minimal sample project reproducing the issue or runnable sample code**
I've created a small demo project with test to reproduce this behavior: https://github.com/markrouz/demo5/blob/main/src/test/java/com/example/demo/Demo5ApplicationTests.java#L23
the first assert is ok, but the second one is failed and I don't understand the reason

Could you please take a look and say if it's bug or I'm doing something wrong?

**Comment by markrouz** [comment]
my bad. I need to increase max.depth setting

**Comment by armandino** [comment]
@markrouz no worries. Thanks for the follow up!
