### ISSUE TITLE
Inherited class fields aren't recognized properly if parent class is not accessible/public

### ISSUE THREAD

**Issue by x80486** [instancio/instancio#1157]
## Description

I have a typical class hierarchy for a project that uses Hibernate. The "base" class is effectively package-private, `abstract`, and contains several "managed" fields. The actual entity classes are `public`.

I'm trying to set all the fields using `Instancio.of` for a given entity:

```java
return Instancio.of(Category.class)
    .set(Select.field(Category::getId), UUID.fromString("SOME-VALID-UUID-VALUE"))
    ...
    .set(Select.field(Category::getName), "Some Name")
    .create();
```

But `Instancio` is unable to find the `id` member for `Category`, unless the parent class is made `public` :grimacing:

## Expected Result

To be able to set all fields/members, as long as they are _visible_ (from method reference).

## Actual Result

```shell
Error creating an object
 -> at org.company.model.internal.CategoryFactory$Persistent.oneOf(CategoryFactory.java:20)

Reason: 

Unable to resolve the field from method reference:
-> CategoryFactory$Persistent::lambda$oneOf$5709d914$1
   at org.company.model.internal.CategoryFactory$Persistent.oneOf(CategoryFactory.java:20)

Potential causes:
-> The method and the corresponding field do not follow expected naming conventions
   See: https://www.instancio.org/user-guide/#method-reference-selector
-> The method is abstract, declared in a superclass, and the field is declared in a subclass
-> The method reference is expressed as a lambda function
   Example:     field((SamplePojo pojo) -> pojo.getValue())
   Instead of:  field(SamplePojo::getValue)
-> You are using Kotlin and passing a method reference of a Kotlin class
```

## Additional Information

```java
// package org.company.model

@Getter
@MappedSuperclass
@NoArgsConstructor(access = AccessLevel.MODULE)
abstract class AbstractPersistable {
  @Id private UUID id;
  ...

  // @PrePersist + @PreUpdate implementations
}

@Getter
@Entity
@Builder
@Table(name = "categories")
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Category extends AbstractPersistable {
  private String name;
  private String description;
  private String picture;
}
```

- Java version: `openjdk 21.0.4 2024-07-16 LTS`
- Instancio version: `5.0.1`

**Comment by armandino** [comment]
@x80486 thanks for raising the issue! Unfortunately Instancio can't resolve the field since it's declared in the parent `AbstractPersistable`. In addition, `AbstractPersistable` is package private, so you can't use `field(AbstractPersistable::getId)` either.

In this case, you could target the `id` field using a predicate selector, e.g.

```java
Select.fields().ofType(UUID.class).named("id")
```

Or if you want to be explicit (in case you have other classes with `UUID id` field) then you can do this:

```java
Select.fields(f -> "id".equals(f.getName())
                && f.getDeclaringClass().getSimpleName().equals("AbstractPersistable"))
```

Here's an example:

```java
@Test
void example() {
    Category res = Instancio.of(Category.class)
            .set(idSelector(), UUID.fromString("dfc5fcdd-a51c-4c94-849c-0e28ca7c45b2"))
            .create();
}

static TargetSelector idSelector() {
    return Select.fields(f -> "id".equals(f.getName())
            && f.getDeclaringClass().getSimpleName().equals("AbstractPersistable"));
}
```

Does this solve your issue?

**Comment by x80486** [comment]
Great! I wasn't sure if there was a way to overcome this. The first solution, `Select.fields().ofType(UUID.class).named("id")` works perfect for my use case.

Thanks! :raised_hands:

**Comment by armandino** [comment]
Awesome! Thanks for the confirmation :+1:
