### ISSUE TITLE
Setting COLLECTION_MIN_SIZE larger than COLLECTION_MAX_SIZE does not raise an error

### ISSUE THREAD

**Issue by StathisKons** [instancio/instancio#1176]
**Describe the bug**
I was playing around with instancio settings and encountered unexpected behaviour. I tried generating a collection with conflicting size limits, ie ``COLLECTION_MIN_SIZE > COLLETCION_MAX_SIZE``

**Expected result**
I expected an error or exception to be thrown, but the program continued executing normally

**Actual result**
It generated collections of various sizes, I believe it only followed the `COLLECTION_MAX_SIZE` property and ignored `COLLECTION_MIN_SIZE`

**Link to a minimal sample project reproducing the issue or runnable sample code**
```java
	List<Foo> foos = Instancio.ofList(Foo.class)
			.size(10)
			.withSettings(Settings.create().set(Keys.COLLECTION_MIN_SIZE, 42).set(Keys.COLLECTION_MAX_SIZE, 24))
			.create();
```
```java
@Getter
@Setter
class Foo {
	private List<String> bar;

	@Override
	public String toString() {
		return "SIZE = " + bar.size() +
				'}';
	}
}
```
generates:
```
SIZE = 20
SIZE = 19
SIZE = 19
SIZE = 15
SIZE = 18
SIZE = 18
SIZE = 22
SIZE = 12
SIZE = 22
SIZE = 14
```

- Java version: 17
- Instancio version:  5.0.1

**Comment by armandino** [comment]
@StathisKons thanks for raising the issue! The min and max settings auto-adjust, so I think it's working as intended:

> When updating range settings, such as COLLECTION_MIN_SIZE and COLLECTION_MAX_SIZE, the range bound is auto-adjusted if the new minimum is higher than the current maximum, and vice versa.

https://www.instancio.org/user-guide/#overriding-settings-programmatically
