### ISSUE TITLE
Please update your documentation to show what imports are needed

### ISSUE THREAD

**Issue by robross0606** [instancio/instancio#1196]
### Feature description

The documentation is strewn with examples of calling things like `field()` without ever explaining where the method came from.  I had to dig through the code base's unit tests to find that this was done with:
```
import static org.instancio.Select.field
```

It would be very nice if you covered this somewhere very obvious and up front in your documentation so users aren't thoroughly confused.

**Comment by armandino** [comment]
Thanks for the suggestion. I can update the docs to include the import (a PR would also be welcome!).
