### ISSUE TITLE
Assignment using getter

### ISSUE THREAD

**Issue by robross0606** [instancio/instancio#1197]
**Describe the bug**
`org.instancio.Select` appears to have options for `field` and `setter`, but no option for `getter`.  Without this, how is it possible to access field data using `Assignment` where the field is private on a parent class while a getter is available via inheritance?

```java
classApi.assign(Assign.valueOf(Select.field("eventDomain")).to(Select.setter("setDescription"))
        .as(d -> "Performed action on " + d + " object."));
```

**Expected result**
The ability to leverage something like `Select.getter("getEventDomain")` to source data for usage in `Assign`.

**Actual result**

```
Error creating an object
...
Reason: invalid field 'eventDomain' for class 
```

If there's a way to do this, I haven't discovered it in the documentation.

**Additional information**
Add any other context about the problem here

**Link to a minimal sample project reproducing the issue or runnable sample code**
```java
// code sample
```

- Java version: 8
- Instancio version: 5.0.2

**Comment by armandino** [comment]
@robross0606 for fields declared in a superclass, you would need to specify the superclass explicitly, e.g. 

```java
Select.field(MySuperclass.class, "eventDomain")
```

Let me know if this solves your issue.

**Comment by robross0606** [comment]
yes, this does appear to allow accessing the data.  Thanks!
