### ISSUE TITLE
Globally customise generated values based on context

### ISSUE THREAD

**Issue by rupert-madden-abbott** [instancio/instancio#212]
Consider the following:

```
class Foo {
  private String name;
}

class Bar {
  private String name;
}
```

I would like to customise how fields called `name` are generated, without having to specify, or even know about, all of the types that have a field called `name`.

At the moment, I would have to write this:

```
var field = field("name");
var generator = gen -> gen.string().mixedCase();

Foo foo = Instancio.of(Foo.class)
    .generate(field, generator)
    .create();
    
Bar bar = Instancio.of(Bar.class)
    .generate(field, generator)
    .create();
```

But I would like to be able to write:

```
Instancio customInstancio = Instancio.customise()
  .generate(matching(field -> field.getName().equals("name"), gen -> gen.string().mixedCase());

Foo foo = customIstancio.create(Foo.class);
Bar bar = customInstancio.create(Bar.class);
```

Equally, I might have this:

```
class Foo {
  @Id
  private String key;
}

class Bar {
  @Id
  private String id;
}
```

I would like to customise how fields annotated with `Id` are generated, without having to specify, or even know about, all of the types that have a field annotated with `Id`.

I would like to be able to write something like this:

```
Instancio customInstancio = Instancio.customise()
  .generate(matching(field -> hasAnnotation(field, Id.class), gen -> gen.string().mixedCase());

Foo foo = customIstancio.create(Foo.class);
Bar bar = customInstancio.create(Bar.class);
```

**Comment by armandino** [comment]
Thanks for the suggestion! That's an interesting idea. To summarise, we want to have more flexibility in selecting fields:

- select fields by name, regardless of the type that declares the field
- select fields annotated with certain annotation(s)

This does open up a potential issue where selected fields are of different types:

```java
class Foo { String code; }
class Bar { Long code; }
```

or

```java
class Foo {  @Id String key; }
class Bar {  @Id String id; }
```

In this case, we may also need to filter by field by type.

My first thought is to use a `Predicate<Field>`, maybe with some syntactic sugar around it. However I will need some time to experiment with the API.

**Comment by armandino** [comment]
@rupert-madden-abbott This should be coming in the next release (1.6.0). There are some examples in the tests in #215.

**Comment by armandino** [comment]
Closing as completed.
