### ISSUE TITLE
Seed not loaded from instancio.properties

### ISSUE THREAD

**Issue by esfomeado** [instancio/instancio#319]
**Describe the bug**
The seed value is not loaded from `instancio.properties`.

It uses always a random one.

**Expected result**
It should use the seed specified on `instancio.properties`.

**Actual result**
Uses a random one.

- Instancio version: 2.2.0

**Comment by armandino** [comment]
@esfomeado could you confirm if your `instancio.properties` is at the root of the classpath? I created a minimal sample project with the seed in the properties:

https://github.com/instancio/instancio-github-issues/tree/main/issue-319

Let me know if you also have a reproducible sample. That would help greatly to figure out what's happening.
