### ISSUE TITLE
String generator should support prefixing strings with field name

### ISSUE THREAD

**Issue by armandino** [instancio/instancio#329]
Current behaviour simply generates random strings. The new feature would allow generating strings prefixed with field name.

For example. `String someField` would produce a string like `"someField_ASFVAF"`

Motivation: make inspecting data and debugging easier.

### Notes

- Current behaviour (i.e. no prefix) will remain as the default
- Field name prefixes can be enabled globally via `instancio.properties` or per object via `Settings`

### Strings that will not be prefixed

- strings provided using `generate()`, `set()`, and `supply()` methods

- `null` strings when "nullable strings" are enabled using any of the following:

```java
withNullable(field(Person::getName))
withSettings(Settings.create().set(Keys.STRING_NULLABLE, true))
```

- Empty strings when "allow empty" is enabled using:

```java
withSettings(Settings.create().set(Keys.STRING_ALLOW_EMPTY, true))
```

**Comment by protyay** [comment]
Is this project looking for contributors ? I'm looking to contribute and open to discuss . Thanks

**Comment by armandino** [comment]
@protyay I'm not sure what you have in mind. If you have a specific idea you'd like to implement, please open a separate issue and we can discuss there. Thanks!
