### ISSUE TITLE
Any plan to add Jakarta Validation and Hibernate Validator support?

### ISSUE THREAD

**Issue by linux-china** [instancio/instancio#370]
Jakarta Validation and Hibernate Validator have lots of annotations of constraints to validate data, and almost I add annotations for fields in class. 

```java
public class User {
    @Positive
    private Long id;
    @UUID
    private String uuid;
    @NotNull
    private String name;
    @Email
    private String email;
    @URL
    private String avatar;
    @Size(min = 6, max = 16)
    private String password;
    private String salt;
    @Size(min = 6, max = 16)
    private String phone;
    private Date createdAt;
}
``` 

Could Instancio generates object by validation annotations?

**Comment by armandino** [comment]
@linux-china, thank you, that's an interesting suggestion. It would definitely be a useful feature.

Looking at https://jakarta.ee/specifications/bean-validation/3.0/apidocs/ I think it should be possible to support most of them. However, I don't see `@URL` and `@UUID`. Are those custom annotations from your project?

**Comment by linux-china** [comment]
@armandino `@URL` and `@UUID` is from Hibernate Validator API https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/package-summary.html, and most developers use Hibernate Validator for validation.

**Comment by armandino** [comment]
@linux-china, got it. Thanks for link. I will look into this.

**Comment by armandino** [comment]
@linux-china, bean validation will be released in the next version. You could also try `2.6.1-SNAPSHOT` for a preview.

```xml
<repositories>
    <repository>
        <id>oss-snapshot-repository</id>
        <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

I added some notes (#380) on which annotations will be supported and how to enable the feature. Please let me know if you try the snapshot or have any feedback.

**Comment by armandino** [comment]
@linux-china, `2.7.0` should be available now.
