### ISSUE TITLE
Collections from Models

### ISSUE THREAD

**Issue by MBoegers** [instancio/instancio#385]
### Feature description
Instances supports generation of collections, which is a nicely crafted easy API. But this API only supports Classes and no `Model<>`. For seems like a break in the API since the actual Class and respected Model are handled interchangeable in the API. 

```java
class Person {
  String name;
  Integer age;
  // constructors and getters omitted
}

// test code as desired 
var youngPersonMode = Instancio.of(Person.class)./* set age to 16 */.toModel();

var youngsters = Instancio.ofList(youngPersonModel);
```

**Comment by armandino** [comment]
@MBoegers I updated the docs. Let me know if you have any other questions.

**Comment by MBoegers** [comment]
@armandino sorry for the delay. Yes, that fits my needs perfectly! And the docs look great

**Comment by armandino** [comment]
@MBoegers, no worries at all. Thank you! :)
