### ISSUE TITLE
TypeVariable is not resolved when using parameterized generic subtype in a class

### ISSUE THREAD

**Issue by dafriedmann** [instancio/instancio#417]
**Describe the bug**
When having a generic subtype inside a class X, Instancio is not able to resolve the TypeVariable to the expected mappedType though the type is parameterized in X. Issue is similar to #202.

**Expected result**
Instancio is able to resolve mappedTypes when using a generic subtype, which is
parameterized over a concrete class.
Instancio is able to set a value for this resolved type.

**Actual result**
Instancio is not able to resolve a type variable, when using a generic subtype.

`[main] WARN org.instancio.internal.nodes.NodeFactory - Unable to resolve type variable 'T'. Parent: Node[GenericDummy.foo, depth=1, #chn=0, GenericFoo<Long>]`

**Additional information**
`NodeFactory#resolveTypeVariable` returns null when confronted with a generic subtype.
The determined mappedType for T such cases is T.
```java
parent.getTypeMap().getOrDefault(typeVar, typeVar)
```
mappedType=T and typeVar=T.
T is therefore resolved with T.

**Sample code reproducing the issue**
```java
public class GenericBar<T> {
    T value;

    public T getValue() {
        return value;
    }
}

public class GenericFoo<T> extends GenericBar<T> {
}

public class Dummy {

    private GenericFoo<Long> foo;

    public GenericFoo<Long> getFoo() {
        return foo;
    }
}
```
The following test fails:
```java
Dummy dummy = Instancio.create(Dummy.class);
assertThat(dummy.getFoo().getValue()).isNotNull(); // fails - value is null
```

Changing the type `GenericFoo` to `GenericBar` inside Dummy (=> Use generic type instead of generic subtype) works well.
In this case T is resolved to Long as mappedType in `NodeFactory#resolveTypeVariable`.

- Instancio version: 2.7.0

**Comment by armandino** [comment]
@dafriedmann, thank you for reporting this, and also for providing all the details. Very much appreciate you input!

I was able to reproduce the issue using your example. I'll look into it and let you know once I have an update.

**Comment by armandino** [comment]
@dafriedmann, the fix will be included in the next release, `2.8.0`. I've accumulated a few bug fixes already, so I will push it out this weekend.

**Comment by dafriedmann** [comment]
Hi @armandino

glad my input was helpful. Many thanks for the quick fix!
Building 2.7.1-SNAPSHOT and testing again looks good.
Even constellations like (one more inheritance) 

```
public class GenericBaz<T> extends GenericFoo<T> {
}
```
are working.
And I have also tried it with 2 TypeParmeters -> Works.

Thanks for your greate work, looking foward to 2.8.0 :)
Meanwhile I will close this issue.

**Comment by armandino** [comment]
@dafriedmann thank you! :) `2.8.0` should be available now from Maven central.
