### ISSUE TITLE
Infinit Loop creating Nodes from many classes with references to eachother

### ISSUE THREAD

**Issue by CommentSectionScientist** [instancio/instancio#429]
**Describe the bug**
We got a pretty huge code base with many classes having Collections with references to eachother.
When creating an object from these entities with Instancio it seems like creating the nodes takes a lot of time (havent seen it finish yet, so infinit loop). (Relatet to Issue #399 )
Changing the Max Depth through the properties file or directly in the Test doesnt change the behaviour, because the maxDepth is only checked when creating/generating the objects in org/instancio/internal/InstancioEngine.java:125.
But the infinit loop seems to be while creating the Nodes in org/instancio/internal/nodes/NodeFactory.java:75
("Stage One" refering to https://github.com/instancio/instancio/issues/391#issuecomment-1419352684)

**Expected result**
- Nodes are only created till the maxDepth is reached(?)
- No infinit loop
- Object is created and populated with data

**Actual result**
"infinit loop"

**Additional information**
I tried restricting the maxDepth or adding several classes to "ignore", but the nodes are still created for these classes

**Sample code reproducing the issue**
Little bit extreme, i know ;)
```java
	@Test
	void instancioShouldCreateObject() {
		// given
		// when
		ObjectA objectA = Instancio.of(ObjectA.class)
				.create();
		// then
		assertThat(objectA).hasNoNullFieldsOrProperties();
	}

	class ObjectA {
		List<ObjectB> objectB;
		List<ObjectC> objectC;
		List<ObjectD> objectD;
		List<ObjectE> objectE;
		List<ObjectF> objectF;
		List<ObjectG> objectG;
	}

	class ObjectB {
		ObjectA objectA;
		ObjectC objectC;
		ObjectD objectD;
		ObjectE objectE;
		ObjectF objectF;
		ObjectG objectG;
	}

	class ObjectC {
		ObjectA objectA;
		ObjectB objectB;
		ObjectD objectD;
		ObjectE objectE;
		ObjectF objectF;
		ObjectG objectG;
	}

	class ObjectD {
		ObjectA objectA;
		ObjectB objectB;
		ObjectC objectC;
		ObjectE objectE;
		ObjectF objectF;
		ObjectG objectG;
	}

	class ObjectE {
		ObjectA objectA;
		ObjectB objectB;
		ObjectC objectC;
		ObjectD objectD;
		ObjectF objectF;
		ObjectG objectG;
	}

	class ObjectF {
		ObjectA objectA;
		ObjectB objectB;
		ObjectC objectC;
		ObjectD objectD;
		ObjectE objectE;
		ObjectG objectG;
	}

	class ObjectG {
		ObjectA objectA;
		ObjectB objectB;
		ObjectC objectC;
		ObjectD objectD;
		ObjectE objectE;
		ObjectF objectF;
	}
```

- Instancio version: 2.8.0

**Comment by armandino** [comment]
@CommentSectionScientist thank you for looking into this and providing a sample. I was able to reproduce the problem.

Yes, unfortunately the max depth setting does not help in this case. I guess the depth check should really be done at the node creation level. I made a bad decision on that one :) I'll experiment a bit to see what we can do here

**Comment by armandino** [comment]
@CommentSectionScientist, @jur-clerkx, @thachlp

I made some changes to try resolve the performance issues you reported. To summarise:

 - max depth checks are now done during node creation
 - the default max depth is now set to `8` (previously default was unlimited)

I would really appreciate if you could provide some feedback using the latest version, `2.9.0`:

- what is the time taken to create your objects using `2.8.0` and `2.9.0`?
- are your objects fully-populated with the default max depth of 8?
- any other thoughts/comments?

**Comment by CommentSectionScientist** [comment]
Damn you are fast 😅
Yes the reproducer provided and the creation of objects of our own classes with lots of references between them works now.

I measured the creation time for one of our classes with a depth ~3 with 2.8.0 and 2.9.0 at around 500ms.

I cant really test one of our classes with lots of references, because with 2.8.0 I aborted the run after several minutes.
In 2.9.0 the object is succesfully created and seems to be sufficiently populated:
with a maxDepth=8: ~35s
with a maxDepth=5: ~1s
with a maxDepth=3: ~0.5s
(I just did multiple runs with JUnit for the measurements, so take these numbers with a grain of salt)

Hope that helps, and thanks again for the fast fix.

**Comment by armandino** [comment]
@CommentSectionScientist thanks very much for the feedback! Glad to hear that the results are better (and that max depth works as a workaround).

I think I will need to spend more time to figure out how to improve the performance further. 35 seconds is quite a long time for a unit test, though I'm not sure how large your classes are. I'll try to come up with some POJOs to replicate this.

Let me know if you run into any other issues :)
