### ISSUE TITLE
Consider OSGI compatibility

### ISSUE THREAD

**Issue by armandino** [instancio/instancio#473]
### Discussed in https://github.com/orgs/instancio/discussions/472

<div type='discussions-op-text'>

<sup>Originally posted by @dwulfert March  1, 2023</sup>
First of all, thank you for your effort. This project seems to be exactly what I was looking for. Unfortunately, I need to integrate the dependency into an OSGI project, which can be quite complicated without integrated bundle information. To make it OSGI compatible, I suggest integrating the maven-bundle-plugin as the only necessary plugin.</div>

**Comment by armandino** [comment]
@dwulfert could you try `2.10.1-SNAPSHOT` and let me know if it works for you?

```xml
<repositories>
    <repository>
        <id>oss-snapshot-repository</id>
        <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by armandino** [comment]
@dwulfert please try the new version `2.11.0`. I will close this issue for now. Feel free to re-open if you're having problems.

**Comment by dwulfert** [comment]
@armandino Big :heart: from me. Thanks, works like a charm.

**Comment by armandino** [comment]
Awesome! Thank you :)
