### ISSUE TITLE
Support record generators via ServiceProvider

### ISSUE THREAD

**Issue by aalbiach-dkt** [instancio/instancio#509]
### Feature description

Generate custom objects for record classes registering the `GeneratorProvider` in the custom `InstancioServiceProvider` implementation as you described [here](https://www.instancio.org/user-guide/#instancio-service-provider-interface).

**Comment by armandino** [comment]
@aalbiach-dkt thank you for reporting this, much appreciated.

It's supposed to work for records, so it's actually a bug. It will be fixed in the next release.

**Comment by armandino** [comment]
@aalbiach-dkt please try version `2.12.0`. It should be available from Maven central now.

Let me know if you're still having problems. I'll close this issue now.

**Comment by aalbiach-dkt** [comment]
It works fine, thank you 😀👌
