### ISSUE TITLE
Ability to configure the suppliers globally. 

### ISSUE THREAD

**Issue by gervaisb** [instancio/instancio#516]
When using Instancio to create arbitrary classes, it would be useful to configure the supplier globally so that we can reuse them or the Instancio instance without having to pass them for each class.

**Actually**
```
for (Class cls : classes) {
  Instancio.of(cls)
    .lenient()
    .supply(....)
    .supply(...)
    .supply(..)
    .create();
}
```

**Expected**
```
Instancio.globally()
    .supply(....)
    .supply(...)
    .supply(..);

for (Class cls : classes) {
  Instancio.create(cls);
}

// OR
Instancio instancio = Instancio
    .supply(....)
    .supply(...)
    .supply(..);

for (Class cls : classes) {
  instancio.create(cls);
}
```

(I do have a favor for the instance)

My use case is that I browse the classpath to collect all classes that should be serialized. Then I instantiate them and test the serialization and deserialization.
However, I have to configure many suppliers to avoid some `null`s and reach some border cases. The code would be much easier to maintain and read without having to configure _Instancio_ for each class.

**Comment by armandino** [comment]
@gervaisb do you have an example of which fields are producing `null` values? Maybe that's something that needs to be fixed. 

Regarding your use case, it should be possible with `InstancioServiceProvider`. There's some documentation on it in this [section](https://www.instancio.org/user-guide/#instancio-service-provider-interface) of the user guide. I also put together a [small sample project](https://github.com/instancio/instancio-samples/tree/main/generator-provider-sample). Using this approach, you can map generators to specific fields or classes, and they will be resolved automatically.

Another alternative would be to use a `Model`:

```java
static <T> Model<T> baseModel(Class<T> klass) {
    return Instancio.of(klass)
        .supply(....)
        .supply(...)
        .supply(..)
        .lenient() // may require lenient if selectors are not common to all classes
        .toModel();
}

SomePojo p1 = Instancio.create(baseModel(SomePojo.class));
OtherPojo p2 = Instancio.create(baseModel(OtherPojo.class));
```

**Comment by gervaisb** [comment]
Our codebase is on Scala, some classes are generated _case class_es with specific construction. Properties of those types are usually `null`.

I do not use a `Model` but I have already moved the configuration of instancio and creation of a class in a dedicated method. 


```
  def create[T](cls: Class[T]): T = {
    Instancio.of(cls).lenient()
      .supply(Select.all(classOf[Set[_]]), () => Set.empty[Any])
      .supply(Select.all(classOf[Option[_]]), () => Option.empty[Any])
      .supply(Select.all(classOf[OneEnumType]), () => OneEnum.Value)
      .supply(Select.all(classOf[OneScalaCaseClass]), () => OneScalaCaseClass(
            AnotherEnum.Value,
            OneNestedComplexType(...),
            Set.empty,
            None
          )
      )
      .create()
  }

  // later
        val origin = create(c)
        val (json, result) = serializeAndDeserialize(origin)
        assert(origin == result, json)
```

What would be the advantage of using a `Model` ?

**Comment by armandino** [comment]
Thanks for providing additional details!

Regarding models, the advantage is that you can [customise objects](https://www.instancio.org/user-guide/#using-models) created from it by adding or updating selectors (e.g. override some selector to a non-null value). But if you only have a single method like `def create[T](cls: Class[T]):` and don't need to customise the objects created from it, then there's no benefit to gain from using a model.

I don't have much experience with Scala, but based on your example I think implementing `GeneratorProvider` will be your best bet. E.g. you can map `classOf(Set[_])` to a generator that returns `Set.empty[Any]`, then using `Instancio.create()` will automatically use the custom generator. Please take a look at the sample project and let me know if you run into any issues.

**Comment by armandino** [comment]
@gervaisb I assume the suggested approach worked for you. I will close the issue for now, but feel free to re-open or add a comment if you're still having problems.
