### ISSUE TITLE
Consider native support for Guava Immutable Collections

### ISSUE THREAD

**Issue by AndrMoiseev** [instancio/instancio#525]
### Feature description
Immutable Value Object is pretty common pattern and if we want truly immutable object - all fields should be immutable as well - including collections. Guava immutable collections looks like frequent choise for implementing this pattern.

Generators can be implemented using SPI, but SPI is pretty limited in its current version - it doesn't have access to Settings or other generation context.

**Comment by armandino** [comment]
@AndrMoiseev thanks for raising this issue. There's no public API available at the moment to implement this. I'll need to spend some time to figure out the best way forward.

There is an internal class `InternalContainerFactoryProvider` that can be used to support `ImmutableMap`, `Table`, etc. Obviously, I _cannot recommend_ using it for production code :) The API is quite likely to change. However, if you're not concerned with breaking changes, I put together a [sample implementation](https://github.com/instancio/instancio-github-issues/tree/main/issue-525).

**Comment by armandino** [comment]
@AndrMoiseev version `2.13.0` with support for Guava should be available now from Maven central. You will need an additional `instancio-guava` dependency on the classpath. Please see #554 for additional details. Let me know if you run into any issues or have any feedback. Thanks!

**Comment by AndrMoiseev** [comment]
@armandino thank you, works like a charm. Deleted my own implementation.

The only very small issue is that values generated for regular collections and Guava collection are different for the same Seed. But it doesn't seem to have any practical consequences.

**Comment by armandino** [comment]
@AndrMoiseev thanks for reporting this!

The library can guarantee the same values to be generated for a given type. If the type changes, then the generated values may change too.

Having said that, this particular case had a straightforward solution, therefore I made some changes that should result in the same values, whether a Guava or regular collection is used (please try version `2.14.0`). However, this is done on a best-effort basis and is not guaranteed to work in future versions. In general, I would not recommend relying on this behaviour in your tests :)

Hope this helps. Let me know if you run into any other issues, or have any other feedback.
