### ISSUE TITLE
Create JPA extension

### ISSUE THREAD

**Issue by Mobe91** [instancio/instancio#526]
### Feature description

Many projects out there are in need for creating JPA entities in tests. This is usually the case for database integration tests where entity objects need to be created and persisted. It can also be the case in business layer unit tests that require entity instances for mocking repository methods.

It would be great if we could use Instancio to create entity instances that can optionally be persisted later on.

```java
Order order = Instancio.of(Order.class)
    .withSettings(Settings.create().set(JpaKeys.METAMODEL, metamodel))
    .create();

entityGraphPersister.persist(order);
```

**Comment by armandino** [comment]
Changes made in the core library to support the extension. Details in #528.

**Comment by Mobe91** [comment]
Hey @armandino, I've added a [comment](https://github.com/instancio/instancio/pull/528#issuecomment-1537358765) to the PR 2 weeks ago. Looks like you haven't seen it, could you take a look? 😄

**Comment by armandino** [comment]
Hi @Mobe91! I saw your comment, but haven't had much time to investigate. I'll look into it soon :)

**Comment by Mobe91** [comment]
For anyone looking for a way to use Instancio with JPA, check [this](https://github.com/Mobe91/instancio-jpa) out.
