### ISSUE TITLE
Make the current Github Actions more friendly towards external contributions

### ISSUE THREAD

**Issue by EvaristeGalois11** [instancio/instancio#540]
Hi, following the discussion under the PR #538 I think it's a good idea to have a dedicated issue to track this problem.

Currently the two workflows don't work for PR submitted from an external fork. This is annoying for contributors like me because we can't reliably know if our contribution broke something and is annoying for you @armandino because you need to test the branch locally to make sure that it isn't really broken. This affects also the deployment of the snapshot: as you can see here https://github.com/instancio/instancio/actions/workflows/deploy-and-verify-snapshots.yml all my PR didn't manage to deploy a snapshot successfully (in this particular case it isn't a problem given that i didn't modify any code, but in general it could lead to a discrepancy between the main branch and the snapshot artifact deployed).

### The root of the problem ###

The main problem lies in the way github actions manage their secrets. All external contributions could potentially be a malicious attack that tries to steal the secrets, so actions on external fork don't have access to them. This is documented here https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow.

Sadly both the workflows rely on some secrets to complete successfully: the `Build` workflow uses the sonar token to publish its analysis and the `Deploy Snapshots` uses the credentials of the repository to deploy its artifact.

### Possible solutions ###
- [x] For the `Deploy Snapshots` workflow one possible solutions is to change the trigger to a push on the main branch instead of the current closing of a PR. This will allow the workflow to run in the main repo in a safe environment and it should have access to the necessary secrets. I found this solution in an official discussion https://github.com/orgs/community/discussions/26724#discussioncomment-3253093. Let me know if you like this approach so I can try to provide a PR for it. #541 

- [x] For the `Build` workflow and more specifically for the SonarCloud access token i don't have a solution yet. From the link you posted i found this thread https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363 that seems to have a few workarounds. I need to study them more carefully to provide a PR. https://github.com/instancio/instancio/pull/547 https://github.com/instancio/instancio/pull/555

Please @armandino feel free to integrate my analysis with your knowledge as the maintainer of the project and of course if it's ok for you if i work on this issue or you prefer to take it upon yourself.

Bye!

**Comment by armandino** [comment]
@EvaristeGalois11 thank you for creating the issue and providing all the details. Much appreciated!

>  For the Deploy Snapshots workflow one possible solutions is to change the trigger to a push on the main branch instead of the current closing of a PR. 

Sounds good to me. I don't see any major downsides to this vs the current approach.

If you're interested in making this change (and possibly the `Build` workflow change later), a PR would be very welcome!
