### ISSUE TITLE
Add support for `Mod10Check` Hibernate annotation

### ISSUE THREAD

**Issue by armandino** [instancio/instancio#567]
### Feature description

>  Allows to validate that a series of digits pass the Mod10 checksum algorithm. The classic Mod10 is calculated by summing up the digits, with every odd digit (from right to left) value multiplied by a multiplier. As example ISBN-13 is Modulo 10 checksum with multiplier = 3.
>
> There are known cases of codes using multipliers for both even and odd digits; To support this kind of implementations the Mod10 constraint uses the weight option, which has the same effect as the multiplier but for even numbers.
>
> The supported type is CharSequence. null is considered valid. 

Source: https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/Mod10Check.html

Since this annotation is available in Hibernate Validator 5, test cases should be included in both:

- `bean-validation-hibernate-tests`
- `bean-validation-hibernate5-tests`

**Comment by EvaristeGalois11** [comment]
Can I take this one?

After the Luhn ones, it just seems a natural continuation :D

**Comment by armandino** [comment]
Sure thing :)
