### ISSUE TITLE
How to set multiple field at the same time?

### ISSUE THREAD

**Issue by akaroice** [instancio/instancio#582]
### Feature description
There are two object - student, class room.
It would be great to have a relation that a student has a class room, but it doens't have. It has olny value of a class room.
- room[0].name = aRoom
- room[0].number = a1
- room[1].name = bRoom
- room[1].number = b2

- student.roomName = aRoom
- student.roomNumber = a1
or
- student.roomName = bRoom
- student.roomNumber = b1

In this case, roomName and roomNumber must match each other in a student.

Would you suggest me how to set multiple field at the same time?
Thanks.

**Comment by armandino** [comment]
@akaroice currently, there's no API for specifying relationships between fields.

There might be workarounds available in some cases, but it's not clear from the example what the classes look like to make a suggestion. Can you provide a code sample of the `Room` and `Student` classes?

**Comment by armandino** [comment]
@akaroice I'll close the issue for now. Feel free to comment if you have any additional information.
