### ISSUE TITLE
Dependant fields

### ISSUE THREAD

**Issue by harissecic** [instancio/instancio#636]
### Feature description

It would be nice to have some relationship between fields when generating them. For example dates in a single instance can require to be one after the other. I've went quickly through code and it might be tough to implement because sequence off generator triggering needs to be preserved.

For example
```java
record RegisterShipment(LocalDateTime start, LocalDateTime end, String address) {}

var test = Instacio.of(RegisterShipment.class)
.generator(field(RegisterShipment::start), gen -> gen.temporal().localDateTime().future())
.generator(field(RegisterShipment::end), gen -> gen.temporal().localDateTime().after(context.field("start"))
.create()
```
Now it would be great if Generator could be ommited and just have something like `context.field(xx).after()` or whatever. Anyway as I said it would require changing generators or having strict sequence of what gets generated first and ability to read it via `onComplete`. Currently `onComplete` for a field won't fire on time to not give null on dependant field like `end`.

Update: what I mean by null value when using `onComplete` is that I was funny enough to try this which of course won't work
```java
var ref = new AtomicReference<LocalDateTime>(null);
record RegisterShipment(LocalDateTime start, LocalDateTime end, String address) {}

var test = Instacio.of(RegisterShipment.class)
.generator(field(RegisterShipment::start), gen -> gen.temporal().localDateTime().future())
.onComplete(field(RegisterShipment::start), (LocalDateTime dateTime) -> {
ref.set(dateTime);
})
.supply(field(RegisterShipment::end), () -> ref.get().plusHours(2))
.create()
```
`ref.get()` is always null in here and I'm using records so there's no good way to predict where to hack this.

Hope I made sense in this request.

**Comment by harissecic** [comment]
Amazing, thanks. Will report back if I get some time to test (and if there's anything to report)

**Comment by harissecic** [comment]
@armandino I just tested what I need right now which is multiple fields depending on each other which works. I can't really think of any other use case to test it a bit more so I just wanted to report it works as far as I can come up with test ideas. Thanks a lot and I guess this issue can be closed as soon it's out of SNAPSHOT state.

**Comment by armandino** [comment]
@harissecic thanks for giving it a try, much appreciated! Yours is the first feedback I got and I'm glad to hear it's positive. I will let you know once v3 is out.

**Comment by armandino** [comment]
@harissecic new release `3.0.0` should be available from Maven central shortly. If you run into any issues, please let me know.

**Comment by harissecic** [comment]
Thanks, much appreciated
