### ISSUE TITLE
When using ofList the max depth of element model is not adjusted

### ISSUE THREAD

**Issue by Mobe91** [instancio/instancio#639]
**Describe the bug**
When creating a list/set/map/stream based on an Instancio Model the maxDepth configured on the model is not adjusted for the additional layer that is added by list/set/map/stream.

Consider the following example:
```java
Model<Order> orderModel = Instancio.of(Order.class).withMaxDepth(3).toModel();
Order order = Instancio.of(orderModel).create();
List<Order> orders = Instancio.ofList(orderModel).size(2).create();
```

**Expected result**
The `order` instance has a maxDepth of 3 as specified in the model definition.
The maxDepth of the order elements in the `orders` list is aligned with the single `order` instance. All instances of Order have a maxDepth of 3 as defined in the model.

**Actual result**
The `order` instance has a maxDepth of 3 as specified in the model definition.
However, the order elements in the `orders` list will each have a maxDepth of only 2 applied. I assume this is because the maxDepth of the collection model created when calling `ofList` is not adjusted for the additional collection layer.

- Instancio version: 2.16.0

**Comment by armandino** [comment]
@Mobe91 thank you for reporting this bug! As a user I would expect the same fields to be populated whether creating an object or a list of objects. This will be fixed in the next release.

**Comment by armandino** [comment]
@Mobe91 please try version `2.16.1`. It should be available shortly once it syncs to Maven central.

**Comment by Mobe91** [comment]
Thanks for the quick fix, it works! 🙂
