### ISSUE TITLE
Support for custom depth strategies

### ISSUE THREAD

**Issue by Mobe91** [instancio/instancio#722]
### Feature description

Currently, Instancio supports the `maxDepth` configuration option to determine/limit the size of the object tree populated by Instancio. Even though this approach works fine in many cases it does not allow for more fine grained control over the depth of the object graph. E.g. there may be cases in which certain branches of an object graph need to be deeper while other branch can remain shallower.

This is especially true in the context of instancio-jpa where the current approach is to compute a minimum depth for yielding a persistable object graph. This minimum depth is then passed to Instancio as `maxDepth`. While this approach works it is far from efficient. Tests with real world entity models show that the minimum depth required usually exceeds 7 and the number of nodes created by Instancio goes into the ten thousands. The majority of these nodes are only created to be thrown away later on. 

Creating a large number of nodes was seen to have an impact on the runtime of tests in the magnitude of seconds.

The support of custom depth strategies could give users (and instancio-jpa) a means to dynamically control the object graph depth on a per branch basis. The current `maxDepth` approach could be abstracted into a default strategy.

A pseudo-interface for a depth strategy could look like this:
```java
public interface DepthStrategy {
  boolean populateBranch(Context context, Node branchRoot);
}

public class MaxDepthStrategy implements DepthStrategy {
  boolean populateBranch(Context context, Node branchRoot) {
    return branchRoot.getDepth() <= context.getSettings().getMaxDepth();
  }
}
```

@armandino If this is something you would consider supporting I would be happy to provide a PR. Let's also discuss other approaches that could solve the root problem.

**Comment by armandino** [comment]
@Mobe91 thanks for the suggestion. This seems like a fairly extensive change. Currently, max depth can be set via:

 - settings using `Keys.MAX_DEPTH`
 - `withMaxDepth()` builder API

with the latter having a higher precedence.

Adding another layer on top of this, where `maxDepth` also depends on a node, will complicate things and create a lot of 
new edge cases. For this reason, I'd rather avoid going down this route.

I think it'd be helpful to see a benchmark that illustrates the performance issue before going into possible solutions.

Any chance you could fork https://github.com/instancio/instancio-benchmark or create a sample project?

Let's compare the results with expectations and take it from there.

**Comment by armandino** [comment]
@Mobe91 are you still experiencing this issue? if so, can you provide a benchmark or a minimal sample project?

**Comment by armandino** [comment]
@Mobe91 no worries at all! Thanks for the update.
