### ISSUE TITLE
Setter of type Collection does not work

### ISSUE THREAD

**Issue by MelleD** [instancio/instancio#730]
**Describe the bug**
First, I don't have a strong opinion whether it's a bug or a new feature.

From my point of view the setter of collection types are not set correctly. For this reason I created a bug

If you have a field with Set/List and a setter with Collection, that setter will be ignored because the types don't exactly match.

However, the setter could be called with a default collection e.g. list.

 Currently, the field is simply set instead to use the setter (depending on the setting of `ON_SET_METHOD_NOT_FOUND`).

**Expected result**
The setter is used

**Actual result**
Field is used or empty collection because will be ignored.

**Additional information**
Workaround is to add a second setter method.

**Link to a minimal sample project reproducing the issue or runnable sample code**
```java
public class Foo {

   private Set<Bar> bars;

   public void setBars( Collection<Bar> bars ) {
      this.bars = createImmutableSet(bars);
   }
```

```
      Instancio.of( Foo.class )
            .withSettings( Settings.create()
                  .set( Keys.ASSIGNMENT_TYPE, AssignmentType.METHOD )
                  //.set( Keys.ON_SET_METHOD_NOT_FOUND, OnSetMethodNotFound.IGNORE )
    );
   }
```

Workaround:

```java
public class Foo {

   private Set<Bar> bars;

   public void setBars( Collection<Bar> bars ) {
      this.bars = createImmutableSet(bars);
   }

   public void setBars( Set<Bar> bars ) {
      this.bars = createImmutableSet(bars);
   }
```

**Comment by armandino** [comment]
Thanks for raising for the issue. It's an interesting use case, however this kind of usage is not supported. Instancio resolves the setter from the field. Therefore, the setter's name _and_ argument type needs to match the field. 

In this example, it's not clear how the matching logic between the field and the setter would work, especially since the setter's argument type, a `Collection`, is not assignable to the field, declared as a `Set`.

Just out of curiosity, can you provide more information about what you're trying to achieve? As you mentioned, it should fallback to populating the value using the field. Does this not work your test case?

**Comment by MelleD** [comment]
> As you mentioned, it should fallback to populating the value using the field. Does this not work for your test case?

No because we do some things on the setter for example to set a relation between domain models . 

> In this example, it's not clear how the matching logic between the field and the setter would work, especially since the setter's argument type, a Collection, is not assignable to the field, declared as a Set.

The logic could be look for a method with match the field and if the Field is assignable from collection. Make a second roundtrip and look for a setter with collection.

**Comment by MelleD** [comment]
@armandino 
Here is one proposal which works
https://github.com/instancio/instancio/pull/733

If you don't want the default behavior, I could also introduce a key setting and maybe even give the base class for the collection or simply a key setting with enable true/false

What do you think?

**Comment by armandino** [comment]
@MelleD thank you for the PR. Although it should address the issue you are facing, it seems too focused on this use case. As an alternative, it might be better to provide an SPI for resolving setters based on fields. I put together a PR (#735) with a sample test based on the example you provided above. Hopefully, this works for you. Let me know if have you have any feedback.

**Comment by MelleD** [comment]
@armandino nice works for me. Thank you.

Do you have a plan for a release :)?

**Comment by MelleD** [comment]
@armandino thanks will try that.
