### ISSUE TITLE
Can't set a value for a field in a interface

### ISSUE THREAD

**Issue by lucasfsousa** [instancio/instancio#746]
**Describe the bug**
I'm trying to `set` a value to an object from an interface that has a `mapType` configured.

I know that we can't use Instancio directly from an interface:
```java
@Test
void shouldReturnNullWhenCreatingAnObjectFromAnInterface() {
    var obj = Instancio.create(FooBarBazInterface.class);
    assertThat(obj).isNull();
}
```

But It's possible if we configure a `mapType`:
```java
@Test
void shouldCreateObjectWhenInterfaceIsMappedToConcreteClass() {
    var obj = Instancio.of(FooBarBazInterface.class)
        .withSettings(
            Settings.create()
                .mapType(FooBarBazInterface.class, ImmutableLombokFooBarBaz.class)
        )
        .create();
    assertThat(obj).isNotNull();
}
```

Unfortunately, we can't `set` a value, even that `mapType` is configured, because the reflection is done in the interface class and there, this field doesn't exist.
```java
@Test
void shouldBeAbleToSetValue() {
    var obj = Instancio.of(FooBarBazInterface.class)
        .withSettings(
            Settings.create().mapType(FooBarBazInterface.class, ImmutableLombokFooBarBaz.class)
        )
        .set(Select.field("bar"), null)
        .create();

    assertThat(obj).isNotNull();
    assertThat(obj.getBar()).isNull();
}
```

**Expected result**
I expect that with `mapType` the reflection is done in the concrete class, not the interface and `set` works as expected.

**Actual result**
```
Error creating an object
 -> at ***.shouldBeAbleToSetValue(InterfaceTest.java:34)

Reason: invalid field 'bar' for interface ***.FooBarBazInterface
```

- Java version: `20.0.2`
- Instancio version: `3.2.0`

**Comment by armandino** [comment]
@lucasfsousa when the field name is specified without a class, Instancio assumes that the field is declared in the root class, for example:

```java
var obj = Instancio.of(FooBarBazInterface.class)
    .set(Select.field("bar"), null)
```

is a shorthand for

```java
var obj = Instancio.of(FooBarBazInterface.class)
    .set(Select.field(FooBarBazInterface.class, "bar"), null)
```

If you specify the class explicitly, it should work as expected:

```java
var obj = Instancio.of(FooBarBazInterface.class)
    .set(Select.field(ImmutableLombokFooBarBaz.class, "bar"), null)
```

**Comment by lucasfsousa** [comment]
@armandino thanks for the quick response (again).
I just tested and it works as you explained.
