### ISSUE TITLE
generating invalid instances

### ISSUE THREAD

**Issue by adrian-herscu** [instancio/instancio#775]
### Feature description

It would be useful to generate an invalid object by supplying a model:

```java
class C {
  public String field1;

  public static Model<C> model() {
    return ... model of C having non nullable field1 with maxLength 10
  }
}

then `Instancio.invalid(C.model()).stream()` would produce C instances with field1=null amd field1 having more than 10 chars.

**Comment by armandino** [comment]
@adrian-herscu thank you for the suggestion. I assume the use case for this feature is to test validation logic. I was thinking about how this might work. It seems to me there could be a lot of cases where it's not clear what "invalid" is, especially when there are selectors for multiple fields (e.g. should one/some/all of them invalid?). Without know the expected result, it will be tricky to make an assertion other than `assertTrue` or `assertFalse`. It will also add quite a bit of complexity to implement such a feature. For this reason, I think it's not worth adding to the library, at least for now.
