### ISSUE TITLE
Support for Bean Validation constraints on getters

### ISSUE THREAD

**Issue by gizmo1177** [instancio/instancio#778]
**Describe the bug**
It seems the Bean Validation Annotations are only respected, when the annotations were added on the beans property. In case the annotations were added to the getter, the data generation based on the constraints doesn´t work.

**Expected result**
In my case a generator generated the bean validation annotations on the getter instead of the property. I expect that the data generation checks the annotations regardless of whether they are added to the property or getter.

**Actual result**
The bean validation annotations are not respected when the data is generated.

**Additional information**
OpenApi generator generates the bean validation annotations on the getter instead on the property itself.

**Link to a minimal sample project reproducing the issue or runnable sample code**
```java
@NotNull @Size(max = 2) 
@Schema(name = "language", requiredMode = Schema.RequiredMode.REQUIRED)
@JsonProperty("language")
public String getLanguage() {
  return language;
}
```

- Java version: 17
- Instancio version: 3.3.1

**Comment by armandino** [comment]
@gizmo1177 thanks for creating this issue. Currently, bean validation annotations are only supported for fields.

The problem with using annotations on getters is that it requires mapping a field to its corresponding getter. This is fine when classes follow a standard naming convention `foo` / `getFoo()`, but this is not always the case, e.g. `foo` / `foo()`, Hungarian notation, etc.

I'll look into this once I have some time.

**Comment by armandino** [comment]
@gizmo1177 please try version `3.4.0` which adds support for constraint annotations on getters (see the example in #781). Let me know if you run into any issues.
