### ISSUE TITLE
Self referencing classes

### ISSUE THREAD

**Issue by harissecic** [instancio/instancio#795]
### Feature description

I realise Instancio will not generate list of dependent "children" in case class A will have field with collection of itself.
Example 
```
@Data
class SomeWrapper {
    private String id;
    private SelfRefClass root;
}
@Data
class SelfRefClass {
  private String id;
  private Set<SelfRefClass> children;
}
```

If you try to use default `create` for instance of type `SelfRefClass` it will skip it but it will also skip if you try it explicitly:
```
Instancio.of(SomeWrapper.class)
    .generate(field(SelfRefClass::getChildren), gen ->  gen.collection().subtype(HashSet.class).size(3))
    .create();
```

I tried also adding scopes like
```
final var rootScope = field(SomeWrapped::getRoot).toScope();
Instancio.of(SomeWrapper .class)
    .generate(field(SelfRefClass::getChildren).within(rootScope), gen ->  gen.collection().subtype(HashSet.class).size(3))
    .create();
```

All example will produce empty collection. In my case I need to generate up to 4 levels of depth. Workaround is to use Instancio for most of fields but then have to manually set all the child objects. Problem is my I need a list of `SomeWrapper` to test a lot of use cases then I need to do list of `SelfRefClass` for each instance of `SomeWrapper`.

Is there something I'm missing or is this feature not available due to possible infinite loop?

**Comment by armandino** [comment]
@harissecic unfortunately creating linked lists or tree-like structures is not supported. I'd suggest populating it manually.

Related:

- #744
