### ISSUE TITLE
Support for VAVR collections

### ISSUE THREAD

**Issue by rfuerst87** [instancio/instancio#823]
### Feature description

We heavily rely on VAVR immutable collections in our codebase. Obviously native support for these collections would be quite helpful for us. Currently we are creating custom generators for our collections, but this is cumbersome and adds boilerplate. Ideally we would have a module similar to `instancio-guava`.

Another option would be to provide some sort of global registry to register custom collection types if you don't want to support VAVR directly. Or is there other alternatives I'm not aware of?

Many thanks anyway for this awesome library!

**Comment by armandino** [comment]
@rfuerst87 thank you for raising this issue!

Unfortunately, the `instancio-guava` module doesn't see much usage. For this reason I'm a bit reluctant to add a VAVR module at this point. In addition, it looks like VAVR v1 is still tagged as alpha. I'd be happy to add a VAVR module at some point in the future if there's enough interest, and once it reaches a stable v1.

In the meantime, do you have an interest in creating an extension library (similar to `instancio-guava`) and publishing it to Maven central?

**Comment by rfuerst87** [comment]
Thanks @armandino for your quick response! I'd consider the current state of vavr as stable. Version 1.0 was meant to be a playground for the devs. Vavr is even officially supported by Spring Data. Anyway, since you cannot support every existing collection library out in the wild your reluctcane is very understandable.

Creating an extension would be an option to consider for us. I just quickly browsed through the source of `instancio-guava` and noticed, that it uses internal apis of `instancio-core`. Is it save to use these as well in an extension? Is there a small guide to kickstart an extension somewhere?

**Comment by armandino** [comment]
> I just quickly browsed through the source of `instancio-guava` and noticed, that it uses internal apis of `instancio-core`. Is it save to use these as well in an extension? Is there a small guide to kickstart an extension somewhere?

Yes, it does rely on an internal class `InternalServiceProvider`. I think it's only one class, so it shouldn't be too bad to refactor if the API changes. The way the internal API is implemented could be improved (it's not intuitive). I haven't had much time to think about it and don't have any good ideas right now, so for the time being, there are no plans to change it.

Unfortunately, there's no guide on how to kickstart an extension. Your best bet is to use the guava module as a reference. Once you get the project started, I'd be happy to help if you run into any issues.

**Comment by rfuerst87** [comment]
Alright, thank you for your insights. I'll wait a little to see how Instancio is being used in our project. If we come up with a vavr extension I will ping you again.

Many thanks for all your efforts!
