### ISSUE TITLE
Generating temporals of specific precision

### ISSUE THREAD

**Issue by foaw** [instancio/instancio#881]
### Feature Description

If truncated temporals—think of instants, for example—are needed, there is no means of changing the precision at the generator level. This means that the unwanted part will have to be discarded manually after the instants are generated.

The preferred option would be to introduce new methods for manipulating precision in `InstantSpec`, `LocalDateTimeSpec`, etc. I think `precision` or `truncatedTo` would make for a good name for it. You may also want to have a corresponding global option in `o.i.s.Keys`.

<details><summary>Usage Example</summary>

```java
_1st: temporal().instant().truncatedTo(ChronoUnit.MICROS);
_2nd: temporal().instant().truncatedTo(TimeUnit.MICROSECONDS);
_3rd: temporal().instant().precision(ChronoUnit.MICROS);
_4th: temporal().instant().precision(TimeUnit.MICROSECONDS);
```
</details>

**Comment by armandino** [comment]
@foaw thank you for the suggestion. It should be possible to achieve this using the `as(Function)` method, e.g.:

```java
temporal().instant().as(i -> i.truncatedTo(ChronoUnit.MICROS))
```

Most built-in generators provide this method to allow mapping from one value to another. Can you give it a try to see if it meets your needs?

**Comment by foaw** [comment]
Judging by its code, it should work. Except that it erases the actual generator type and returns a generic `GeneratorSpec<T>`, but that's trivia. Still, it would be nice if someday there were a method that could convey this intention more clearly. :-)

**Comment by armandino** [comment]
I agree it'd make the API a little nicer. I'll keep this to investigate a bit more.

**Comment by armandino** [comment]
@foaw this will be included in `4.2.0`.

**Comment by armandino** [comment]
@foaw just released `4.2.0`. Please give it a try.

**Comment by foaw** [comment]
Just gave it a try. Switched over to `InstantGenerator#truncatedTo` and it works like a charm!

Off-topic: when updating I noticed the major version went up. Does Instancio have a change log aside from `git log <release-1>..<release-2>`?

**Comment by armandino** [comment]
The release page has the changelog: https://github.com/instancio/instancio/releases
