### ISSUE TITLE
User-defined generators and models in tests

### ISSUE THREAD

**Issue by foaw** [instancio/instancio#886]
### Feature description

If a test is a parametrized one and `@InstancioSource` is applied, sets of data will be provided as parameters for the test, generated randomly. The problem is that you cannot bring your own models or generators. The only remaining option is to resort to generating data manually, which is:

- Cumbersome, as it brings no practical value to the test—merely explodes the "set-up part" of tests.
- Does not report what was supplied as arguments.
- Obfuscates the true nature of parametrized tests, as it's no longer a `@ParametrizedTest` but a `@Test`. (Even if marked as parametrized, without any parameters, it remains just as obscure.)

Perhaps I'm being overzealous in pushing this so hard and some points may be over-exaggerated. Still, I think this would be great to have an option to hide the data generation and not do it directly in tests.

As for possible implementation, we already have `@WithSettings` where you could assign custom generators for types. However, this is rather inflexible, and in my specific case it wouldn't be enough to bind one type to one generator.

We can have semi-qualifier annotations like `@PersonRandom` or `@PersonRandom.Adult` and associate that with `Generator`s/`GeneratorSpec`s. This approach will admittedly still lack the flexibility of programmatic solutions, but it's closest we can get with Java of 2024.

```java
@ExtendWith(InstancioExtension.class)
class PutOrderTest {

    @WithSettings
    final Settings settings = Settings.create()
        .generator(OrderRandom.class, orderRandom -> { ... })
        .generator(PersonRandom.class, personRandom -> { ... });

    @ParameterizedTest
    @InstancioSource
    void putOrderMinor(@OrderRandom(adultOriented = true)
                       Order order,
                       @PersonRandom(age = PersonRandom.Age.ADULT)
                       Person person)
    { /* ... */ }
}
```

**Comment by armandino** [comment]
> Still, I think this would be great to have an option to hide the data generation and not do it directly in tests.

Thanks for the suggestion. If I understood correctly, the goal is to move setup logic outside the test method.

> The problem is that you cannot bring your own models or generators. The only remaining option is to resort to generating data manually

You can declare a model as a field or return it from a method, e.g.

```java
@ExtendWith(InstancioExtension.class)
class PutOrderTest {

    private final Model<Person> adultModel = Instancio.of(Person.class)
            .generate(field(Person::getAge), gen -> gen.ints().min(18))
            .toModel();

    private final Model<Order> orderModel = Instancio.of(Order.class)
            // ...
            .toModel();

    @Test
    void putOrderMinor() {
        Person adult = Instancio.create(adultModel);
        Order order = Instancio.create(orderModel);
         // ...
    }
}
```

Another option is to use [`instancio-quickcheck`](https://www.instancio.org/user-guide/#quickcheck). Here's an example that mimics your code sample.

```java
class PutOrderTest {

    @Property(samples = 100)
    void putOrderMinor(@ForAll("adultOrders") Order order,
                       @ForAll("adults") Person adult) {

        assertThat(adult.getAge()).isGreaterThanOrEqualTo(18);
        // etc...
    }

    private Arbitrary<Person> adults() {
        return Arbitrary.fromStream(
                Instancio.of(Person.class)
                        .generate(field(Person::getAge), gen -> gen.ints().min(18))
                        .stream());
    }

    private Arbitrary<Order> adultOrders() {
        return Arbitrary.fromStream(Stream.empty()); // TODO generate orders
    }
}
```

Quickcheck is a new module, introduced in version `3.6.0`, and is currently labeled as an experimental feature.

**Comment by armandino** [comment]
@foaw I'll close the issue. Feel free to add a comment if the above didn't work for you.

**Comment by foaw** [comment]
Frankly, I haven't yet had the opportunity to modify the tests where I needed this.

- This doesn't seem very flexible, not as much as annotations. For every set of options in an annotation, this approach needs a new method. Is this correct, am I missing something?
- How do you reference a supplier from another class, say an outer class or a designated class for just suppliers. Or do you duplicate them as needed for better "locality" and looser coupling?

**Comment by armandino** [comment]
@foaw I'm not fully sure what you're trying to accomplish. Maybe another example might help?

Regarding custom annotations, it's not clear how `@PersonRandom(age = PersonRandom.Age.ADULT)` can be mapped to a generator, e.g. `ints().range(18, ??)`.

**Comment by foaw** [comment]
So, I have tests for different scenarios with POJOs specialised in some way. For example, in the context of a store recommendation algorithm, given an underage user and a list of products, some of which are only for adults, the minors shouldn't be recommended the adult products.

In my business domain, I have maybe around ten such conditions. Instead of having a method for each set of possible combinations, I'd rather write an annotation and an interpreter for it, which knows how to transform an annotation into a generator, or how to populate generator settings from an annotation.

This implies that there will always be a new generator for each test. Just like when you do it manually: create the generator, configure it for your needs, generate a value. The proposal is basically to take the configuration part out of test code.

**Comment by armandino** [comment]
Thanks for the additional info. Let me start with the last question. The use case for models is to create a predefined template for generating objects, that can be reused and customised as needed. I described this in more detail in this [article](https://www.instancio.org/articles/creating-object-templates-using-models). Generators are typically for value types, though you could define them for POJOs as well. E.g. you could define a `Generator<Customer>` that can be used as follows:

`supply(all(Customer.class), customer().adult().status(ACTIVE))`

You can also a combination of custom generators and models. I can't say what the best approach is without knowing the domain classes and test case requirements. I do recall the discussion post where you mentioned that using models didn't meet your requirements because the class had several interdependent fields. My response to that is that it might be easier to construct the objects manually for such cases.

To circle back to the annotations:

```java
    @ParameterizedTest
    @InstancioSource
    void putOrderMinor(@OrderRandom(adultOriented = true)
                       Order order,
                       @PersonRandom(age = PersonRandom.Age.ADULT)
                       Person person)
```

Since these annotations are specific to your domain, I don't see how the library would be aware of the custom annotation attributes? You can probably achieve this by implementing a JUnit 5 extension that inspects the annotations and its attributes, and creates an object based on those values. I'm not sure if that's worth the effort though :) If you create a sample project with your domain classes, I could look into this a bit more.
