### ISSUE TITLE
`lenient()` mode should ignore unconsumed `.emit().items()`

### ISSUE THREAD

**Issue by dcebotarenco** [instancio/instancio#933]
### Feature description

Suppose you have a model

```java
Model validModel;
void setup() {
  validModel = Instancio.of(Type.class)
  .generate(field(a), gen -> gen.collection().size(2))
  .generate(field(a), gen -> gen.emit().items(true, false))
  .set(all(field(b), false))
  .toModel();
}

@Test
void myTest() {
 Instancio.of(validModel).
.lenient() //for overriding the set
.set(all(field(b), true))
.generate(field(a), gen -> gen.collection().size(0))
.create(); // will fail cause emit values were not consumed
}
```

I have to change the model by adding `gen.emit().items(true, false).ignoreUnused()`
This would allow me to use the **One Bad Attribute** pattern and not forgetting the `ignoreUnused`

**Comment by armandino** [comment]
I think this change will violate separation of concerns. The `lenient()` method is used to ignore unused selectors. It's not related to generators. Any reason why you can't add `ignoreUnused()` to the model?
