### ISSUE TITLE
How to generate a list of strings from a pre-defined selection

### ISSUE THREAD

**Issue by tschmidt01** [instancio/instancio#935]
Having a class like this:
```
@Data
private static class SomeClass {
    private String someString;
    private List<String> someStrings;
}
```

It is possible to generate a value for `someString` from a predefined selection by using

```
var result = Instancio.of(SomeClass.class)
    .generate(field(SomeClass::getSomeString), gen -> gen.oneOf("A", "B", "C"))
    .create();
```

How to do the same for `someStrings`? I was looking for the possibility to delegate the item generation for a `collection()` generator to another generator (like `oneOf()`) but could not find any possibilities to achieve this.

**Comment by armandino** [comment]
You should be able to do this using `Select.scope()` to select strings within `SomeClass2::getSomeStrings`.

```java
.generate(allStrings().within(scope(SomeClass2::getSomeStrings)), gen -> gen.oneOf("A", "B", "C"))
```
