### ISSUE TITLE
GeneratorProvider ordering

### ISSUE THREAD

**Issue by resourcify-dev** [instancio/instancio#949]
### Feature description

I have now stumbled upon numerous scenarios where it would be good to be able to define the precedence / ordering between custom GeneratorProviders. E.g. a libarary like instancio-jpa provides certain out-of-the-box generator providers that are picked up automatically via ServiceLoader. However, a user may want to overrule the behavior they provide. Currently, I am not aware of a good way of doing that.

So I suggest to extend the GeneratorProvider interface as follows:
```java
    interface GeneratorProvider {

        GeneratorSpec<?> getGenerator(Node node, Generators generators);

        int getOrder();
    }
```
to allow to user to define a total order among third party and custom generator providers.
Maybe there is a better way to do this. A disadvantage of this approach is that it is not possible to order generator providers provided by multiple third party libraries.

So maybe allowing to establish run-before relations would be better.
```java
    interface GeneratorProvider {

        GeneratorSpec<?> getGenerator(Node node, Generators generators);

        Class<? extends GeneratorProvider> runBefore();
    }
```

**Comment by armandino** [comment]
I believe SPI implementations should be picked based on the classpath order. For example, if we have a Maven test module that imports `instancio-jpa` (SPI implementation **A**), and our test module also has its own SPI implementation **B**, then generators provided by **B** should take take precedence over **A**. If **B** returns null for a given node, then it should fall back to **A**. So we'll have this order:

- Generator from B (if defined)
- Generator from A (if defined)
- Generator from Instancio

Can you confirm whether it works this way in your project? If not, it'd be great if you could provide a minimal sample project as an example.
