### ISSUE TITLE
Spatial Generator

### ISSUE THREAD

**Issue by StevenPG** [instancio/instancio#951]
### Feature description

A new generator dedicated to spatial data. 

Anyone looking to utilize instancio for spatial/GIS projects would need to use the DoubleSpec with a hardcoded min/max for latitude and longitude. It gets a little repetitive and error-prone in a large project with many different spatial objects.

#### Examples

    SpatialObject spatial = Instancio.of(SpatialObject.class)
        // ex. Implicitly limit latitude as a double between -90 to 90
        .generate(field(SpatialObject::getLatitude), gen -> gen.spatial.lat())
        // ex. Implicitly limit longitude as -180 to 180 and provide a static or range of precision
        .generate(field(SpatialObject::getLongitude), gen -> gen.spatial.lon().precision(7))

This could also potentially support degrees,minutes,seconds for geographic coordinates.
       
This is a simple baseline for "spatial" type data. There's opportunity to expand this in the future with generating GeoJson, which is a very common way to represent areas on a map. (https://geojson.io/)

GeoJson is used in a lot of geospatial libraries as a working layer and for visualization, so plenty of custom objects developers create hold onto geojson.

The main question is what to use for the representation. Not sure if Jackson JsonNode is a great idea or not.

Also I'm open to pick up this work myself. My team has been using instancio and we'd make heavy use of this new generator and spec!

**Comment by armandino** [comment]
Thank you for the suggestion. I think it will be a good addition.

If other types of data are added under `spatial()` in the future, would it make sense to group lat/lon under `coordinate()` or `point()`? e.g.

1. `gen.spatial().coordinate().lon()`
1. `gen.spatial().point().lon()`

It would be good to have a list of potential methods that might be added in the future and some examples of data they would generate (I'd like to avoid very niche data though and stick with things that are common, like lat/lon).

**Comment by StevenPG** [comment]
Yeah absolutely grouping under `coordinate()` would be ideal for lat/lon.

There's a few samples I can provide that a spatial generator could grow into:

WKT and GeoJson are very portable and used across many GIS tools and implementations

## WKT - Well Known Text Representation

There's a bunch of WKT examples on the wiki page. But the ability to generate complicated shapes would be useful for anyone building GIS applications.
(https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry)

1. `gen.spatial().wkt().point()` -> POINT (30 10)
2. `gen.spatial().wkt().polygon(5)` -> POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))
3. `gen.spatial().wkt().point(39, 41, 145, 155)` -> POINT(45 150)

## GeoJson

1. `gen.spatial().geojson().point()` -> 
```
    {
        "coordinates": [
          20.849573066512846,
          50.190760721311904
        ],
        "type": "Point"
      }
```

2. `gen.spatial().geojson().polygon()` ->
```
{
        "coordinates": [
          [
            [
              18.388635566512846,
              37.03738153702169
            ],
            [
              14.873010566512505,
              35.47830164839911
            ],
            [
              19.091760566512733,
              34.03418461611774
            ],
            [
              18.388635566512846,
              37.03738153702169
            ]
          ]
        ],
        "type": "Polygon"
      }
```

**Comment by armandino** [comment]
Thank you for the examples!

Let's add lat/lon for now. Not sure whether `point()` or `coordinate()` is better. The former has the advantage of being shorter.

A PR would be welcome if you have the time to submit one (if you do, please check out [building](https://github.com/instancio/instancio/blob/main/website/docs/building.md) and [contributing](https://github.com/instancio/instancio/blob/main/CONTRIBUTING.md) pages).

**Comment by StevenPG** [comment]
Absolutely! I'll get something drafted up this weekend.

Technically speaking, latitude and longitude are each a coordinate that make up a point.

My vote is for `.coordinate()` for that reason! Either way, I'll get a PR out and adjustments can be made.

**Comment by StevenPG** [comment]
Added https://github.com/instancio/instancio/pull/953 as a first pass.

I'd love to expand on this, but wanted to get out a baseline implementation.
